name: Swift

on:
  push:
    branches: 
      - '**'        # matches every branch
  pull_request:
    branches:
      - '**'        # matches every branch

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild  -project Fuel.xcodeproj -scheme Fuel -sdk iphoneos CODE_SIGNING_ALLOWED=NO build
    - name: Run tests
      run: xcodebuild -project Fuel.xcodeproj -scheme Fuel -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' test
